/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

using RosSharp.RosBridgeClient.MessageTypes.Std;
using RosSharp.RosBridgeClient.MessageTypes.MapCreator;

namespace RosSharp.RosBridgeClient.MessageTypes.MapCreator
{
    public class WorkSpace : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "map_creator/WorkSpace";

        public Header header;
        public WsSphere[] WsSpheres;
        public float resolution;

        public WorkSpace()
        {
            this.header = new Header();
            this.WsSpheres = new WsSphere[0];
            this.resolution = 0.0f;
        }

        public WorkSpace(Header header, WsSphere[] WsSpheres, float resolution)
        {
            this.header = header;
            this.WsSpheres = WsSpheres;
            this.resolution = resolution;
        }
    }
}
