/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

using RosSharp.RosBridgeClient.MessageTypes.Std;
using RosSharp.RosBridgeClient.MessageTypes.Geometry;

namespace RosSharp.RosBridgeClient.MessageTypes.MapCreator
{
    public class WsSphere : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "map_creator/WsSphere";

        public Header header;
        public Point32 point;
        public float ri;
        public Pose[] poses;

        public WsSphere()
        {
            this.header = new Header();
            this.point = new Point32();
            this.ri = 0.0f;
            this.poses = new Pose[0];
        }

        public WsSphere(Header header, Point32 point, float ri, Pose[] poses)
        {
            this.header = header;
            this.point = point;
            this.ri = ri;
            this.poses = poses;
        }
    }
}
